
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/DevelopTools/JetBrainsToolbox/apps/CLion/ch-0/232.9559.58/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/DevelopTools/JetBrainsToolbox/apps/CLion/ch-0/232.9559.58/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/DevelopTools/JetBrainsToolbox/apps/CLion/ch-0/232.9559.58/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/DevelopTools/JetBrainsToolbox/apps/CLion/ch-0/232.9559.58/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/DevelopTools/JetBrainsToolbox/apps/CLion/ch-0/232.9559.58/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
